# 1.1 수학과 파이썬 복습

## 1.1.1 벡터와 행렬

* 벡터 
<br> 크기와 방향을 가진 양
<br> 1차원 배열로 표현 가능

* 행렬
<br> 2차원 배열로 표현 가능

* 텐서
<br> 벡터와 행렬을 확장하여 N차원 배열로 표현한 것

In [10]:
import numpy as np

x = np.array([1, 2, 3])     # 벡터 생성
x. __class__        # 클래스 이름 표시

numpy.ndarray

np.array() 메서드는 넘파이의 다차원 배열 클래스인 np.ndarray 클래스를 생성한다.

In [11]:
x.shape     # 형상 확인

(3,)

In [12]:
x.ndim      # 차원 확인

1

In [13]:
W = np.array([[1, 2, 3], [4, 5, 6]])    # 행렬 생성
W.shape     # 형상 확인

(2, 3)

In [14]:
W.ndim      # 차원 확인

2

## 1.1.2 행렬의 원소별 연산

* 원소별 연산(elementwise)
<br> 같은 위치의 원소끼리 연산이 이루어진다.

In [19]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [20]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

##1.1.3 브로드캐스트

* 브로드캐스트
<br> 형상이 다른 배열끼리도 연산이 가능하게하는 기능

In [22]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

위의 코드를 보면 2x2행렬에 스칼라 값 10이 곱해졌다.
<br>이 때 스칼라 값 10이 브로드캐스트 기능에 의해 2x2행렬로 확장된 후 elementwise 연산이 수행된다.

In [24]:
A = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

##1.1.4 벡터의 내적과 행렬의 곱

* 벡터의 내적<br>
두 벡터에서 대응하는 원소들의 곱을 모두 더한 것<br>
Let $X = (x_1, x_2,\dots,x_n)$, $Y = (y_1, y_2,\dots,y_n)$. <br> 
Then $X \bullet Y = x_1y_1+x_2y_2 + \dots + x_ny_n$

NOTE
<br> 벡터의 내적은 '두 벡터가 얼마나 같은 방향을 향하고 있는가'를 나타낸다.
<br> 벡터의 길이가 1인 경우, 방향이 같을 경우 내적의 값이 1이고, 방향이 반대이면 내적의 값이 -1이다.

* 행렬의 곱
<br> 왼쪽 행렬의 행벡터와 오른쪽 행렬의 열벡터의 내적

In [29]:
# 벡터의 내적(np.dot 메서드 이용)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)    # 1*4 + 2*5 + 3*6 = 32

32

In [32]:
# 행렬의 곱(np.matmul 메서드 이용)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.matmul(A, B)     # 1*5 + 2*7 = 19
                    # 1*6 + 2*8 = 22
                    # 3*5 + 4*7 = 43
                    # 3*6 + 4*8 = 50

array([[19, 22],
       [43, 50]])

In [33]:
# 행렬의 곱(np.dot 메서드 이용)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)     # 1*5 + 2*7 = 19
                    # 1*6 + 2*8 = 22
                    # 3*5 + 4*7 = 43
                    # 3*6 + 4*8 = 50

array([[19, 22],
       [43, 50]])

##1.1.5 행렬 형상 확인

* 형상 확인
<br> 행렬 A x 행렬 B = 행렬 C일 때,
<br> 행렬 C의 형상은 (행렬 A의 행 수) by (행렬 B의 열 수)

행렬의 곱에서는 대응하는 차원의 원소 수가 같아야 하므로 형상 확인이 매우 중요하다.